### PR TITLE
add testing in CI

### PR DESCRIPTION
**Pull request by sliemeobn**

### CODE REVIEW

**Review by MahdiBM — COMMENTED** [review]
You should use Vapor's reusable CI IMO:

```yaml
name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ main ] }
  
jobs:
  unit-tests:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    secrets: inherit
```

See Vapor's own CI: https://github.com/vapor/vapor/blob/main/.github/workflows/test.yml

**Comment by MahdiBM** [comment]
There might be some issues but i'll help you resolve them, if needed ... no sure if a CodeCov token is needed to be added manually, or maybe tsan will make the CI fail ... we can solve them with some 1-line adjustments in the CI file.

**Comment by sliemeobn** [comment]
@MahdiBM oh, cool, didn't know that existed ; )
let me try...

---
hmm... on first look it hard-codes swift 5.8 and 5.9, which won't work.
so not sure how to proceed, I think merge this for now and we can sort out a more sophisticated setup later?

**Comment by MahdiBM** [comment]
@sliemeobn not a problem, it won't run the tests for unsupported Swift versions.

**Comment by sliemeobn** [comment]
https://github.com/vapor-community/vapor-elementary/pull/2

**Pull request merged**
